line-length = 88
cache-dir = ".ruff_cache"
target-version = "py312"
unsafe-fixes = true
show-fixes = true


[lint.isort]
lines-between-types = 1
order-by-type = true

[format]
preview = true
quote-style = "single"
docstring-code-format = true
skip-magic-trailing-comma = false
