name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    name: 'Build 🏗'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.HUB_GITHUB_TOKEN }}

    - name: Build the Docker image
      run:
        | # 使用 上一步写的 Dockerfile 构建镜像并发布到私有仓库； 发布完成可以去 https://github.com/MrGaoGang?tab=packages 查看
        docker build . --file Dockerfile --tag ghcr.io/wieszheng/bread-image:latest
        docker push ghcr.io/wieszheng/bread-image:latest
